default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: santhosh_parkeasy
  password: parkeasymobile
  host: localhost
  port: 5432

development:
  <<: *default
  database: santhosh_parkeasy_dev

test:
  <<: *default
  database: santhosh_parkeasy_test

production:
  <<: *default
  database: santhosh_parkeasy_production
